### ISSUE TITLE
DeepLIFTWrapper Correction Suggested

### ISSUE THREAD

**Issue by vedhas** [albermax/innvestigate#127]
I believe there is a **code correction** necessary in [DeepLIFTWrapper](https://github.com/albermax/innvestigate/blob/master/innvestigate/analyzer/deeplift.py) 

If I understand this correctly (jump to point 4, if in hurry) : 
1.  [`analyze()`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L314) takes in `X` as the input feature matrix=[d0,d1,d2...d(m-1)]. 
2. `X` can also simply be a 2D numpy array, where the 0th dimension size corresponds to `N`=number of instances, or data samples in X, while 1st dimension size corresponds to `F`=number of features or dimensionality of the feature space.
3. If one is interested in finding relevance of different input features for a regression task with a single output, batch_size for the analyser should be = N = X[0].
(As the final layer consists of only one neuron, thus shape [batch_size, 1 ], while input layer shape = [batch_size, X[1] ]=[batch_size, F])
4.  However, [`X = iutils.to_list(X)`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L318) = makes [`X=[X,]`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/utils/__init__.py#L39), implying `len(X)=1`.
5. Thus, for [`analysis`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L336) calculated at `line 336`, i.e. for 
`analysis = self._analyze_with_deeplift(X, neuron_idx, len(X))`
`batch_size = 1`, which should have been actually `N` (for [`_analyze_with_deeplift()`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L307))
6. Invoking analyzer results in error at:
[`tmp = np.stack([a[i] for a in analysis]).reshape(x.shape)`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L350)
`ValueError: cannot reshape array of size 521 into shape (20836,521)`. 
That is, basically,
`tmp = np.stack([a[i] for a in analysis]).reshape(x.shape)`
`ValueError: cannot reshape array of size F into shape (N,F)`
7. To rootcause the error, I printed out `np.array(X).shape`, `np.array(x).shape`, `np.array(analysis).shape` and `np.array(analysis[0]).shape)`.
I find that:
`np.array(X).shape=(1, 20836, 521)`, 
`np.array(x).shape=(20836, 521)`, 
`np.array(analysis).shape=(1, 20836, 521)` and 
`np.array(analysis[0]).shape)=(20836, 521)`.
**In summary `analysis` and `X` are, as a result, iterables with length 1, should have been of length `N` I think.**

* As a quick fix, I have added following lines to the code before [`ret=[]`](https://github.com/albermax/innvestigate/blob/eb766f017a00fe5d13e4e26089eed5f1dfc4b503/innvestigate/analyzer/deeplift.py#L348)
```
if len(analysis)==1:
        ret = analysis[0]
        return np.array(ret)
```
FYI, I invoke different analysers using 
```
for method in methods:
        analyzer = innvestigate.create_analyzer(method, new_model,
                                neuron_selection_mode="index")
        analyzers.append(analyzer)
for aidx, analyzer in enumerate(analyzers):
        myanalysis=analyzer.analyze(Test[SelectInstances,:],0)
```
`myanalysis` is, thus, a numpy array, and I face no problem generating it with LRP.Z or input_gradient etc. other analyzers. I am not sure though, that DeepLiftWrapper is calculating the contributions from the features correctly with the so-called fix I have implemented. Kindly advise.

**Comment by vedhas** [comment]
With this modification, I notice that feature contributions as computed by DeepLiftWrapper are same as that by LRP.Z, and are same as input*gradient. 

The DeepLift reference point = root point (i.e. where f(x)=0) = the feature vector with all zeros.

**Comment by albermax** [comment]
Hi Vedas,

thank you for the detailed post!!
1. Yes, it can be either single tensor X (thus also a matrix) or a *list* of tensors [X1, X2, ..., Xn] like in Keras. This should have the same format as the Xs for a Keras model.
2. Yes.
3. Not sure if I can follow. The output of the model should have nothing to do with the input shape??
4. Is putting X in a canonical format as it can be also a list of tensors (See answer to 1.)
5. Yes, you are right! This should be `analysis = self._analyze_with_deeplift(X, neuron_idx, len(X[0))` and best one would check that `assert all(len(X[0]) == len(x) for x in x])`. Thank you for noting!
6. I think this another bug :-/

Ok, I see there are some inconsistencies in this code.
Thank you for pointing them out!

I will fix it soon! And your fix should work (if you use batch_size=1 otherwise you need to change the code as pointed out in 5.)

> With this modification, I notice that feature contributions as computed by DeepLiftWrapper are same as that by LRP.Z, and are same as input*gradient.
> 
> The DeepLift reference point = root point (i.e. where f(x)=0) = the feature vector with all zeros.

This can happen! LRP-Z is equal to input*gradient, if the network only consists ReLU-activations and Max-Pooling layers. And in that case it is also very close to DeepLift. Thus I think your results are correct.
Here you can read more about it:
* https://arxiv.org/abs/1711.06104
* https://arxiv.org/abs/1611.07270

Cheers,
Max

**Comment by vedhas** [comment]
Point number 3. refers to only the fact that batch_size = N = Number of instances or inputs = Number of labels or outputs.

**Comment by albermax** [comment]
I see!

Could you please test the fix? It is added to the develop branch.
