### ISSUE TITLE
LRP-Z = LRP gamma?

### ISSUE THREAD

**Issue by daviddliu** [albermax/innvestigate#245]
Is LRP-Z the same thing as "LRP gamma"? I can't seem to find LRP-Z in the literature, just want to make sure. Thanks!

**Comment by sebastian-lapuschkin** [comment]
Dear @daviddliu, 

LRP-Z is the most basic LRP decomposition rule, initially published in [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0130140) as Eq. 56.
The Term LRP-Z appears and is explained [here](https://ieeexplore.ieee.org/document/9206975) in disambiguation ([alternative open access link](http://iphome.hhi.de/samek/pdf/KohIJCNN20.pdf)).
Since LRP-Z is identical to LRP-epsilon with epsilon=0, it is sometimes referred to LRP-0, [e.g. here](https://link.springer.com/chapter/10.1007/978-3-030-28954-6_10), see Appendix 10.A). This link will also clarify how LRP-Z (or LRP-0) and LRP-gamma differ.

**Comment by daviddliu** [comment]
Hi @sebastian-lapuschkin  thank you for your work on this library, and for the links. The last one is especially helpful. So if I am understanding correctly, LRP-gamma is currently not implemented? Thanks!

**Comment by leanderweber** [comment]
Hi @daviddliu,

in this branch (https://github.com/albermax/innvestigate/tree/updates_towards_tf2.0), 
LRP-gamma is already implemented. 

In the final Innvestigate 2 version,
LRP-gamma will definitely also be included!

**Comment by daviddliu** [comment]
Thank you both!
