### ISSUE TITLE
Clarification of the type of network to use

### ISSUE THREAD

**Issue by adebayoj** [albermax/innvestigate#95]
Hi, 

Thank you for open sourcing this package. It must be a lot of work. I have some questions. 

I am trying to use PatternNet and PatternAttribution with any predefined network, i.e., if I define my own tensorflow graph (or keras) with regular ops, is there a way to use your library to get the 'explanation' on an input for PatternNet and PatternAttribution?

I ask this because I would like to see the output of PatternNet for Inception v3 and two small networks (2 convs + 2 fully connected layers) on MNIST. However, as it stands, I am unsure how to go about using your library to do that. 

Secondly, for the other methods, I would like to modify your demos (the ones in your notebooks), to arbitrary architectures could you point me to where I can see where this is done? 

Thanks for great work.

**Comment by albermax** [comment]
Hi Julius,

Thanks!

You need to pass a Keras model class. This means the network needs to be build with Keras layers. Otherwise the code cannot infer the model graph anymore.
Thus if you mean TF ops with regular ops, no. What you can do is train the model with TF and only for the analysis rebuild it Keras and set the weights.

Right now PatternNet and PatternAttribution is only available for VGG-style networks (as those are the only ones that conform with the assumptions in the paper). Therefore it will not work with InceptionV3, but it should with the small networks. Though we are working on extending PatternNet to other networks.

To modify it to arbitrary architectures just replace the Keras model that gets passed to the analyzer class with your custom Keras model.

I hope this helps! Please let me know if you have more questions.
Cheers,
Max

**Comment by adebayoj** [comment]
Great, thanks for the feedback. 

Just to clarify, if I use a conv->pool->conv->pool->fc->fc(output) network structure, is patternet and pattern activation defined for this network? Just clarifying so that I don't make the wrong conclusions. 

Thanks.

**Comment by albermax** [comment]
Yes, that should work. In general the analyzer class should throw an exception if you use layers that are not supported! Mind to use ReLU-pattern-types in case you use ReLUs.
